server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:localhost.p12
        key-store-password: "IngWeb2" # Use the same export password you setwhen creating the PKCS#12 file
        key-store-type: PKCS12
    http2:
        enabled: true